#:schema node_modules/wrangler/config-schema.json
main = "index.html"
compatibility_date = "2024-09-03"
compatibility_flags = ["nodejs_compat"]
#pages_build_output_dir = "./dist"


###############################################################################
## ENV: DEV 
###############################################################################

name = "faithcopilot-lite-app"

[vars]
FAITHCOPILOT_URL = "https://api-staging.faithcopilot.com/api/v1/chat/completions"
FAITHCOPILOT_CHAT_PROFILE_ID = ""
